project/Bctpython/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache, cache_page
from frontpages import views
from .views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^quickbooks/', include('quickbooks.urls')),

    url(r'^$', views.home,  name='home'),

    url(r'^gallery/', cache_page(60 * 30)(views.GalleryInstagramView.as_view()),  name='gallery'),
    url(r'^yourtrips/', views.yourtrips, name='yourtrips'),
    url(r'^westeuro/', views.westeuro,  name='westeuro'),
    url(r'^easteuro/', views.easteuro, name='easteuro'),
    url(r'^scandinavia/', views.scandinavia,  name='scandinavia'),
    url(r'^kilimanjaro/', views.kilimanjaro, name='kilimanjaro'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.faqs, name='faqs'),
    url(r'^privacy/', views.privacy, name='privacy'),
    url(r'^thankyou/', views.thankyou, name='thankyou'),

    # about pages: terms, info pages, etc.
    url(r'^about/', views.about, name='about'),
    url(r'^included/', views.included,  name='included'),
    url(r'^packing/', views.packing, name='packing'),
    url(r'^accommodations/', views.accommodations, name='accommodations'),
    url(r'^guides/', views.guides,  name='guides'),
    url(r'^reviews/', views.reviews,  name='reviews'),
    url(r'^terms/', views.terms, name='terms'),
    url(r'^premium/', views.AboutPremiumView.as_view(), name='premium'),

    # ckeditor urls with rewrited decorators (staff required - standard decorator)
    url(r'^upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    # stripe webhooks
    url(r'webhooks/$', webhooks, name='webhooks'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'frontpages.views.handler400'
handler403 = 'frontpages.views.handler403'
handler404 = 'frontpages.views.handler404'
handler500 = 'frontpages.views.handler500'

project/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    # Account home page
    url(r'^$', views.UserHomePageView.as_view(), name='home'),
    url(r'public/(?P<pk>[-\w]+)/$', views.UserPublicView.as_view(), name='public-home'),
    url(r'^membership/$', views.UserMembershipView.as_view(), name='membership'),
    url(r'^membership/payment/$', views.membership_payment, name='membership_payment'),
    url(r'^membership/payment-success/$', views.PremiumMembershipPaymentSuccessView.as_view(),
        name='membership_success'),

    url(r'^trip/(?P<pk>[-\w]+)/$', views.UserTripDetail.as_view(), name='trip'),
    url(r'^payment-success/$', views.TripPaymentSuccessView.as_view(), name='trip_success'),
    url(r'^create-post/$', views.UserBlogPostCreateView.as_view(), name='create_blog_post'),
    url(r'^create-post/thanks/$', views.UserBlogPostCreatedView.as_view(), name='blog_post_created'),
    # url(r'^trip/$', views.usertripdetail, name='trip2'),
    # User sign up and account activation via email address
    url(r'^signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^account-activation-sent/$', views.account_activation_sent, name='account_activation_sent'),

    # Login and Logout pages for account
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logout'),

    # Update pages for User and Account models
    url(r'^update-account/$', views.AccountUpdate.as_view(), name='update_account'),
    url(r'^update-user/$', views.UserUpdate.as_view(), name='update_user'),

    # URLs for password change. password_change - page with form to input old password.
    url(r'^password-change/$', views.UserPasswordChangeView.as_view(), name='password_change'),
    url(r'^password-change-done/$', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    # URLs for password reset ('forgot password' functionality). _reset and _confirm - pages with forms
    url(r'^password-reset/$', views.UserPasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset-done/$', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password-reset-complete/$', views.UserPasswordResetComplete.as_view(), name='password_reset_complete'),

]

project/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogHomePageView.as_view(), name='home'),
    url(r'^(?P<pk>[-\w]+)/$', views.BlogPostPageView.as_view(), name='blog_post'),
]

project/lib/django/conf/project_template/project_name/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

project/lib/django/contrib/gis/db/backends/base/models.py
import re

from django.contrib.gis import gdal
from django.utils import six
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class SpatialRefSysMixin(object):
    """
    The SpatialRefSysMixin is a class used by the database-dependent
    SpatialRefSys objects to reduce redundant code.
    """
    # For pulling out the spheroid from the spatial reference string. This
    # regular expression is used only if the user does not have GDAL installed.
    # TODO: Flattening not used in all ellipsoids, could also be a minor axis,
    # or 'b' parameter.
    spheroid_regex = re.compile(r'.+SPHEROID\[\"(?P<name>.+)\",(?P<major>\d+(\.\d+)?),(?P<flattening>\d{3}\.\d+),')

    # For pulling out the units on platforms w/o GDAL installed.
    # TODO: Figure out how to pull out angular units of projected coordinate system and
    # fix for LOCAL_CS types.  GDAL should be highly recommended for performing
    # distance queries.
    units_regex = re.compile(
        r'.+UNIT ?\["(?P<unit_name>[\w \'\(\)]+)", ?(?P<unit>[\d\.]+)'
        r'(,AUTHORITY\["(?P<unit_auth_name>[\w \'\(\)]+)",'
        r'"(?P<unit_auth_val>\d+)"\])?\]([\w ]+)?(,'
        r'AUTHORITY\["(?P<auth_name>[\w \'\(\)]+)","(?P<auth_val>\d+)"\])?\]$'
    )

    @property
    def srs(self):
        """
        Returns a GDAL SpatialReference object, if GDAL is installed.
        """
        if gdal.HAS_GDAL:
            # TODO: Is caching really necessary here?  Is complexity worth it?
            if hasattr(self, '_srs'):
                # Returning a clone of the cached SpatialReference object.
                return self._srs.clone()
            else:
                # Attempting to cache a SpatialReference object.

                # Trying to get from WKT first.
                try:
                    self._srs = gdal.SpatialReference(self.wkt)
                    return self.srs
                except Exception as msg:
                    pass

                try:
                    self._srs = gdal.SpatialReference(self.proj4text)
                    return self.srs
                except Exception as msg:
                    pass

                raise Exception('Could not get OSR SpatialReference from WKT: %s\nError:\n%s' % (self.wkt, msg))
        else:
            raise Exception('GDAL is not installed.')

    @property
    def ellipsoid(self):
        """
        Returns a tuple of the ellipsoid parameters:
        (semimajor axis, semiminor axis, and inverse flattening).
        """
        if gdal.HAS_GDAL:
            return self.srs.ellipsoid
        else:
            m = self.spheroid_regex.match(self.wkt)
            if m:
                return (float(m.group('major')), float(m.group('flattening')))
            else:
                return None

    @property
    def name(self):
        "Returns the projection name."
        return self.srs.name

    @property
    def spheroid(self):
        "Returns the spheroid name for this spatial reference."
        return self.srs['spheroid']

    @property
    def datum(self):
        "Returns the datum for this spatial reference."
        return self.srs['datum']

    @property
    def projected(self):
        "Is this Spatial Reference projected?"
        if gdal.HAS_GDAL:
            return self.srs.projected
        else:
            return self.wkt.startswith('PROJCS')

    @property
    def local(self):
        "Is this Spatial Reference local?"
        if gdal.HAS_GDAL:
            return self.srs.local
        else:
            return self.wkt.startswith('LOCAL_CS')

    @property
    def geographic(self):
        "Is this Spatial Reference geographic?"
        if gdal.HAS_GDAL:
            return self.srs.geographic
        else:
            return self.wkt.startswith('GEOGCS')

    @property
    def linear_name(self):
        "Returns the linear units name."
        if gdal.HAS_GDAL:
            return self.srs.linear_name
        elif self.geographic:
            return None
        else:
            m = self.units_regex.match(self.wkt)
            return m.group('unit_name')

    @property
    def linear_units(self):
        "Returns the linear units."
        if gdal.HAS_GDAL:
            return self.srs.linear_units
        elif self.geographic:
            return None
        else:
            m = self.units_regex.match(self.wkt)
            return m.group('unit')

    @property
    def angular_name(self):
        "Returns the name of the angular units."
        if gdal.HAS_GDAL:
            return self.srs.angular_name
        elif self.projected:
            return None
        else:
            m = self.units_regex.match(self.wkt)
            return m.group('unit_name')

    @property
    def angular_units(self):
        "Returns the angular units."
        if gdal.HAS_GDAL:
            return self.srs.angular_units
        elif self.projected:
            return None
        else:
            m = self.units_regex.match(self.wkt)
            return m.group('unit')

    @property
    def units(self):
        "Returns a tuple of the units and the name."
        if self.projected or self.local:
            return (self.linear_units, self.linear_name)
        elif self.geographic:
            return (self.angular_units, self.angular_name)
        else:
            return (None, None)

    @classmethod
    def get_units(cls, wkt):
        """
        Class method used by GeometryField on initialization to
        retrieve the units on the given WKT, without having to use
        any of the database fields.
        """
        if gdal.HAS_GDAL:
            return gdal.SpatialReference(wkt).units
        else:
            m = cls.units_regex.match(wkt)
            return m.group('unit'), m.group('unit_name')

    @classmethod
    def get_spheroid(cls, wkt, string=True):
        """
        Class method used by GeometryField on initialization to
        retrieve the `SPHEROID[..]` parameters from the given WKT.
        """
        if gdal.HAS_GDAL:
            srs = gdal.SpatialReference(wkt)
            sphere_params = srs.ellipsoid
            sphere_name = srs['spheroid']
        else:
            m = cls.spheroid_regex.match(wkt)
            if m:
                sphere_params = (float(m.group('major')), float(m.group('flattening')))
                sphere_name = m.group('name')
            else:
                return None

        if not string:
            return sphere_name, sphere_params
        else:
            # `string` parameter used to place in format acceptable by PostGIS
            if len(sphere_params) == 3:
                radius, flattening = sphere_params[0], sphere_params[2]
            else:
                radius, flattening = sphere_params
            return 'SPHEROID["%s",%s,%s]' % (sphere_name, radius, flattening)

    def __str__(self):
        """
        Returns the string representation.  If GDAL is installed,
        it will be 'pretty' OGC WKT.
        """
        try:
            return six.text_type(self.srs)
        except Exception:
            return six.text_type(self.wkt)

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <base href="/">

    <meta http-equiv=“Content-Type” content=“text/html; charset=utf-8”>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="trQ4WhLvZLsyiy0teiyrePRoWHKHvACueuuJqxa6WgE"/>

    <link rel="shortcut icon" type="image/png" href="{% static 'bc-flav.fw.png' %}"/>
    <title>Black Crow Tours {% block head_title %}{% endblock %}</title>


    <!-- Google Mdl -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'material.min.css' %}"/>
    <script defer src="{% static 'material.min.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>

    {% include 'includes/analytics.html' %}

    {% include 'includes/facebook_pixel.html' %}

</head>
<body>
{% include 'includes/social_widgets_js.html' %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

    <!-- Header -->
    <header id="bc-main-navigation__header-style" class="mdl-layout__header">
        <div id="bc-navigation-height-style" class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title"><a href="{% url 'home' %}">
                    <img id="bc-logo-style" src="{% static 'Mainlogosite1.fw.png' %}" alt=""></a>
                </span>

            <div class="mdl-layout-spacer"></div>

            <!-- Navigation -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"
                   id="bc-navigation-font-style" href="{% url 'yourtrips' %}">Your Trips</a>
                <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"
                   id="bc-navigation-font-style-about">About</a>

                <!-- sub menu only visible when clicked on the link above -->

                <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                    for="bc-navigation-font-style-about">
                    <a class="bc-navigation-subfont-style" href="{% url 'about' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Our Mission</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'premium' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Premium Membership</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'included' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">What's Included?</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'packing' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">What to Pack?</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'accommodations' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Your Accommodations</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'guides' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Your Guides</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'reviews' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Reviews</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'terms' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Terms</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'blog:home' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Blog</li>
                    </a>
                </ul>

                <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"
                   id="bc-navigation-font-style" href="{% url 'gallery' %}">Gallery</a>
{#                <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"#}
{#                   id="bc-navigation-font-style" href="#">Shop</a>#}

                {% if request.user.is_authenticated %}
                    <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"
                       id="bc-navigation-font-style-account">Account</a>

                    <!-- sub menu only visible when clicked on the link above -->

                    <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                        for="bc-navigation-font-style-account">
                        <a class="bc-navigation-subfont-style" href="{% url 'accounts:home' %}">
                            <li class="mdl-menu__item bc-navigation-subfont-style">My account</li>
                        </a>
                        <a class="bc-navigation-subfont-style" href="{% url 'accounts:password_change' %}">
                            <li class="mdl-menu__item bc-navigation-subfont-style">Change password</li>
                        </a>
                        <a class="bc-navigation-subfont-style" href="{% url 'accounts:logout' %}">
                            <li class="mdl-menu__item bc-navigation-subfont-style">Logout</li>
                        </a>
                    </ul>
                {% else %}
                    <a class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect"
                       id="bc-navigation-font-style" href="{% url 'accounts:home' %}">Account</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
            <span class="mdl-layout-title"><a href="{% url 'home' %}">
                <img id="bc-drawer-logo-style" src="{% static 'BC tours Icon.fw.png' %}" alt=""></a>
            </span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style" href="{% url 'yourtrips' %}">Your
                Trips</a>
            <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style-about">About Us</a>

            <!-- sub menu only visible when clicked on the link above -->

            <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                for="bc-navigation-drawer-font-style-about">
                <a class="bc-navigation-subfont-style" href="{% url 'about' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Our Mission</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'premium' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Premium Membership</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'included' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">What's Included?</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'packing' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">What to Pack?</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'accommodations' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Your Accommodations</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'guides' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Your Guides</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'reviews' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Reviews</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'terms' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Terms</li>
                </a>
                <a class="bc-navigation-subfont-style" href="{% url 'blog:home' %}">
                    <li class="mdl-menu__item bc-navigation-subfont-style">Blog</li>
                </a>
            </ul>

            <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style" href="{% url 'gallery' %}">Gallery</a>
{#            <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style" href="#">Shop</a>#}
            {% if request.user.is_authenticated %}
                <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style-account">Account</a>

                <!-- sub menu only visible when clicked on the link above -->

                <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                    for="bc-navigation-drawer-font-style-account">
                    <a class="bc-navigation-subfont-style" href="{% url 'accounts:home' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">My account</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'accounts:password_change' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Change Password</li>
                    </a>
                    <a class="bc-navigation-subfont-style" href="{% url 'accounts:logout' %}">
                        <li class="mdl-menu__item bc-navigation-subfont-style">Logout</li>
                    </a>
                </ul>

            {% else %}
                <a class="mdl-navigation__link" id="bc-navigation-drawer-font-style" href="{% url 'accounts:home' %}">Account</a>
            {% endif %}

        </nav>
    </div>

    <main class="mdl-layout__content">

        {% block content %}

        {% endblock %}

        <!-- Footer -->
        <div class="mdl-grid bc-footer-background">
            <div class="mdl-layout-spacer"></div>
            <div class="mdl-cell mdl-cell--1-col bc-text-center mdl-cell--middle">
                    <span><a href="https://www.facebook.com/Blackcrowtours/" target="_blank">
                        <img class="bc-standard-img-icons" src="{% static 'icons/fb.fw.png' %}" alt=""></a>
                    </span>
            </div>
            <div class="mdl-cell mdl-cell--1-col bc-text-center mdl-cell--middle">
                    <span><a href="https://www.instagram.com/blackcrowtours/" target="_blank">
                        <img class="bc-standard-img-icons" src="{% static 'icons/insta.fw.png' %}" alt=""></a>
                    </span>
            </div>
            <div class="mdl-cell mdl-cell--1-col bc-text-center mdl-cell--middle">
                    <span><a href="{% url 'faqs' %}">
                        <img class="bc-standard-img-icons" src="{% static 'icons/faq.fw.png' %}" alt=""></a>
                    </span>
            </div>
            <div class="mdl-cell mdl-cell--1-col bc-text-center mdl-cell--middle">
                    <span><a href="mailto:admin@blackcrowtours.com">
                        <img class="bc-standard-img-icons" src="{% static 'icons/mail.fw.png' %}" alt=""></a></span>
            </div>
            <div class="mdl-layout-spacer"></div>
        </div> <!--End Footer -->

        <!-- copyright -->
        <div class="mdl-grid bc-site-dark-background">
            <div class="mdl-layout-spacer"></div>
            <h4 class="bc-home-icon-text">&copy; Copyright 2017 Black Crow Tours</h4>
            <div class="mdl-layout-spacer"></div>
        </div>

        <script type="text/javascript">
            var trackcmp_email = '';
            var trackcmp = document.createElement("script");
            trackcmp.async = true;
            trackcmp.type = 'text/javascript';
            trackcmp.src = '//trackcmp.net/visit?actid=89326834&e=' + encodeURIComponent(trackcmp_email) + '&r=' + encodeURIComponent(document.referrer) + '&u=' + encodeURIComponent(window.location.href);
            var trackcmp_s = document.getElementsByTagName("script");
            if (trackcmp_s.length) {
                trackcmp_s[0].parentNode.appendChild(trackcmp);
            } else {
                var trackcmp_h = document.getElementsByTagName("head");
                trackcmp_h.length && trackcmp_h[0].appendChild(trackcmp);
            }
        </script>

    </main>
</div>
</body>
</html>