project/Bctpython/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache, cache_page
from frontpages import views
from .views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^quickbooks/', include('quickbooks.urls')),

    url(r'^$', views.home,  name='home'),

    url(r'^gallery/', cache_page(60 * 30)(views.GalleryInstagramView.as_view()),  name='gallery'),
    url(r'^yourtrips/', views.yourtrips, name='yourtrips'),
    url(r'^westeuro/', views.westeuro,  name='westeuro'),
    url(r'^easteuro/', views.easteuro, name='easteuro'),
    url(r'^scandinavia/', views.scandinavia,  name='scandinavia'),
    url(r'^kilimanjaro/', views.kilimanjaro, name='kilimanjaro'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.faqs, name='faqs'),
    url(r'^privacy/', views.privacy, name='privacy'),
    url(r'^thankyou/', views.thankyou, name='thankyou'),

    # about pages: terms, info pages, etc.
    url(r'^about/', views.about, name='about'),
    url(r'^included/', views.included,  name='included'),
    url(r'^packing/', views.packing, name='packing'),
    url(r'^accommodations/', views.accommodations, name='accommodations'),
    url(r'^guides/', views.guides,  name='guides'),
    url(r'^reviews/', views.reviews,  name='reviews'),
    url(r'^terms/', views.terms, name='terms'),
    url(r'^premium/', views.AboutPremiumView.as_view(), name='premium'),

    # ckeditor urls with rewrited decorators (staff required - standard decorator)
    url(r'^upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    # stripe webhooks
    url(r'webhooks/$', webhooks, name='webhooks'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'frontpages.views.handler400'
handler403 = 'frontpages.views.handler403'
handler404 = 'frontpages.views.handler404'
handler500 = 'frontpages.views.handler500'

project/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    # Account home page
    url(r'^$', views.UserHomePageView.as_view(), name='home'),
    url(r'public/(?P<pk>[-\w]+)/$', views.UserPublicView.as_view(), name='public-home'),
    url(r'^membership/$', views.UserMembershipView.as_view(), name='membership'),
    url(r'^membership/payment/$', views.membership_payment, name='membership_payment'),
    url(r'^membership/payment-success/$', views.PremiumMembershipPaymentSuccessView.as_view(),
        name='membership_success'),

    url(r'^trip/(?P<pk>[-\w]+)/$', views.UserTripDetail.as_view(), name='trip'),
    url(r'^payment-success/$', views.TripPaymentSuccessView.as_view(), name='trip_success'),
    url(r'^create-post/$', views.UserBlogPostCreateView.as_view(), name='create_blog_post'),
    url(r'^create-post/thanks/$', views.UserBlogPostCreatedView.as_view(), name='blog_post_created'),
    # url(r'^trip/$', views.usertripdetail, name='trip2'),
    # User sign up and account activation via email address
    url(r'^signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^account-activation-sent/$', views.account_activation_sent, name='account_activation_sent'),

    # Login and Logout pages for account
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logout'),

    # Update pages for User and Account models
    url(r'^update-account/$', views.AccountUpdate.as_view(), name='update_account'),
    url(r'^update-user/$', views.UserUpdate.as_view(), name='update_user'),

    # URLs for password change. password_change - page with form to input old password.
    url(r'^password-change/$', views.UserPasswordChangeView.as_view(), name='password_change'),
    url(r'^password-change-done/$', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    # URLs for password reset ('forgot password' functionality). _reset and _confirm - pages with forms
    url(r'^password-reset/$', views.UserPasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset-done/$', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password-reset-complete/$', views.UserPasswordResetComplete.as_view(), name='password_reset_complete'),

]

project/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogHomePageView.as_view(), name='home'),
    url(r'^(?P<pk>[-\w]+)/$', views.BlogPostPageView.as_view(), name='blog_post'),
]

project/lib/django/conf/project_template/project_name/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

project/frontpages/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.views import TemplateView
from .instagram_api import GetUserMedia


class GalleryInstagramView(TemplateView):
    template_name = 'frontpages/gallery.html'

    def get_context_data(self, **kwargs):
        context = super(GalleryInstagramView, self).get_context_data(**kwargs)
        # You can set how many photos will be shown in settings file
        context['photos'] = GetUserMedia.recent_media(settings.INSTAGRAM_SHOW_MEDIA_COUNT)
        return context


class AboutPremiumView(TemplateView):
    template_name = 'frontpages/about/premium.html'

    def get_context_data(self, **kwargs):
        context = super(AboutPremiumView, self).get_context_data(**kwargs)
        context['premium_membership_price'] = settings.PREMIUM_MEMBERSHIP_PRICE
        return context


def about(request):
    return render(request, 'frontpages/about/about.html')


def home(request):
    return render(request, 'frontpages/index.html')


def yourtrips(request):
    return render(request, 'frontpages/yourtrips.html')


def accommodations(request):
    return render(request, 'frontpages/about/accommodations.html')


def guides(request):
    return render(request, 'frontpages/about/guides.html')


def included(request):
    return render(request, 'frontpages/about/included.html')


def terms(request):
    return render(request, 'frontpages/about/terms.html')


def privacy(request):
    return render(request, 'frontpages/privacy.html')


def packing(request):
    return render(request, 'frontpages/about/packing.html')


def thankyou(request):
    return render(request, 'frontpages/thankyou.html')


def faqs(request):
    return render(request, 'frontpages/faqs.html')


def easteuro(request):
    return render(request, 'frontpages/easteuro.html')


def westeuro(request):
    return render(request, 'frontpages/westeuro.html')


def scandinavia(request):
    return render(request, 'frontpages/scandinavia.html')


def kilimanjaro(request):
    return render(request, 'frontpages/kilimanjaro.html')


def reviews(request):
    return render(request, 'frontpages/about/reviews.html')


def contact(request):
    return render(request, 'frontpages/contact.html')


# Views for custom errors pages: 400, 403, 404, 500
def handler400(request):
    return render(request, 'frontpages/errors/400.html', status=400)


def handler403(request):
    return render(request, 'frontpages/errors/403.html', status=403)


def handler404(request):
    return render(request, 'frontpages/errors/404.html', status=404)


def handler500(request):
    return render(request, 'frontpages/errors/500.html', status=500)

project/templates/frontpages/about/about.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- About{% endblock %}

{% block content %}

    <!-- Top hero section -->
    <div class="mdl-grid bc-about-main-hero">
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell mdl-cell--10-col">
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <h4 class="bc-about-heading bc-text-center"><br><br><br>Black Crow Tours is a
                        <br><span class="bc-about-heading-bold bc-text-center">backpacking-inspired tour company</span>
                        <br>for young adults ages 21-35</h4>
                </div>
            </div>
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col mdl-cell--bottom mdl-cell--hide-phone">
                    <br><br><br><br><br><br><br><br><br><br>
                </div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col mdl-cell--bottom">
                    <h4 class="bc-header-text bc-text-center">We specialize in providing intimate small-group guided
                        tours
                        <br>focused on local experiences.</h4>

                </div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col mdl-cell--bottom mdl-cell--hide-phone">
                    <br><br><br><br>
                </div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col mdl-cell--bottom">
                    <h4 class="bc-about-subheading bc-text-center">About us:</h4>

                </div>
            </div>

        </div>
        <div class="mdl-layout-spacer"></div>
    </div>


    <!-- 2nd section -->
    <div class="mdl-grid bc-about-mission">
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell mdl-cell--10-col">
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <h4 class="bc-about-para-text">At Black Crow Tours we focus on meeting fun, local people and seeing
                        local culture while providing the best
                        tour package value for people in our demographic:</h4>
                </div>
            </div>
            <div class="mdl-grid">
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-phone bc-text-center">
                    <img class="bc-standard-img-icons" src="{% static 'icons/person.png' %}" alt="">
                    <h4 class="bc-about-para-italic-text bc-text-center">Small group sizes allow for
                        truly unique experiences. </h4>
                </div>
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-phone mdl-cell--hide-tablet bc-text-center">
                    <img class="bc-standard-img-icons" src="{% static 'icons/guide.png' %}" alt="">
                    <h4 class="bc-about-para-italic-text bc-text-center">Guides have the freedom
                        to be themselves, for pure and honest tours. </h4>

                </div>
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-phone bc-text-center">
                    <img class="bc-standard-img-icons" src="{% static 'icons/air.png' %}" alt="">
                    <h4 class="bc-about-para-italic-text bc-text-center">Trips all include flights,transfers, bookings,
                        accommodations, and much more </h4>

                </div>
                <div class="mdl-layout-spacer"></div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <h4 class="bc-about-para-text"> Each trip gives you the option of 'Short' or 'Regular', because we
                        respect your time and this way most friends
                        can also go; even those who might not be able to take off as much time... But don't worry if
                        you're coming alone!
                        Plenty of people do, and always leave with a ton of new friends!

                        <br><br>We believe that life is too short to not do amazing things, and, as young adults, life
                        is both an adventure and a party.
                        This is why most trips also feature a local event you'll have an option to join; an event your
                        guide personally enjoys.

                        <br><br>Join us on our next adventure!</h4>
                </div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <br>
                </div>
            </div>

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <h4 class="bc-about-subheading">WHY 'BLACK CROW'?</h4>
                    <h4 class="bc-about-para-text">The name "BlackCrow" was chosen because crows are one of the smartest
                        birds on the planet. Crows are capable of building tools and working together to achieve goals.

                        <br><br>They are found everywhere on earth, can eat anything, and are one of the few animals
                        thriving with human contact.

                        <br><br>Yet, for some reason, crows have a stigma of being grim. BlackCrow strives to be a tool
                        for helping people to think differently about life. Where society sees something strange; we see
                        intelligence, prosperity, and freedom.</h4>
                </div>
                <div class="mdl-layout-spacer"></div>
            </div>


        </div>
        <div class="mdl-layout-spacer"></div>
    </div>



{% endblock %}

project/templates/frontpages/about/accommodations.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Accommodations{% endblock %}

{% block content %}

    <!-- hero -->
    <div class="mdl-grid bc-accom-hero">
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-cell mdl-cell--10-col mdl-cell--middle">
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--8-col">
                    <h4 class="bc-accom-heading">AT BLACK CROW, WE'LL BE
                        STAYING IN A MIXTURE OF
                        BOUTIQUE HOSTELS, HOTELS,
                        AND CUSTOM ARANGED
                        MANSIONS.</h4>

                    <br><br><br><br>

                    <h4 class="bc-accom-subheading">All to give good variation throughout the trip,
                        which is ultimately decided by the tour director
                        to create the best and most unique trip possible.

                        <br><br>Some people might be confused as to what is
                        included or what the facilities may look like,
                        so we want to help!</h4>
                </div>
                <div class="mdl-layout-spacer"></div>
            </div>
        </div>
        <div class="mdl-layout-spacer"></div>
    </div>

    <!-- accom include -->
    <div class="mdl-grid bc-accom-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--10-col">

            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">

                    <div class="mdl-grid">
                        <div class="mdl-cell mdl-cell--12-col">
                            <h4 class="bc-accom-sub-title bc-text-center">Accommodations include:</h4>
                        </div>
                    </div>
                </div>
            </div>

            <!-- features -->
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--4-col">
                    <h4 class="bc-accom-text bc-no-margin">
                        <strong> - 24 Hour Reception </strong>
                        <br><strong> - 24 Hour Security (No Curfew!) </strong>
                        <br> - Bars (Attached)
                        <br> - Games (Board games, pool tables, etc...)
                        <br><strong> - Great locations! (Extremely Central) </strong>
                        <br> - At least one free meal or welcome drink
                        <br> - Cafes and Guest Kitchen
                        <br> - Common Rooms
                        <br> - Free City Maps
                        <br><strong> - Free Internet Access / WiFi </strong>
                        <br> - Hair Dryers For Hire
                        <br> - Hot Showers
                        <br> - Housekeeping
                        <br> - Key Card Access
                    </h4>
                </div>

                <div class="mdl-cell mdl-cell--4-col">
                    <h4 class="bc-accom-text bc-no-margin">
                        <strong> - 24 Hour Reception </strong>
                        <br><strong> - 24 Hour Security (No Curfew!) </strong>
                        <br> - Bars (Attached)
                        <br> - Games (Board games, pool tables, etc...)
                        <br><strong> - Great locations! (Extremely Central) </strong>
                        <br> - At least one free meal or welcome drink
                        <br> - Cafes and Guest Kitchen
                        <br> - Common Rooms
                        <br> - Free City Maps
                        <br><strong> - Free Internet Access / WiFi </strong>
                        <br> - Hair Dryers For Hire
                        <br> - Hot Showers
                        <br> - Housekeeping
                        <br> - Key Card Access
                    </h4>
                </div>

                <div class="mdl-cell mdl-cell--4-col">
                    <h4 class="bc-accom-text bc-no-margin">
                        <strong> - Laundry Facilities </strong>
                        <br><strong> - Linen and Pillow Included </strong>
                        <br><strong> - Individual Security Lockers </strong>
                        <br> - Luggage Storage
                        <br> - Reading Lights
                        <br> <strong>- Rooming ONLY with our group </strong>
                        <br> - Travel Advice Desk
                        <br> - Towels for hire
                        <br> - Some include Pools, Spa's, and Sauna's
                        <br> - Fitness centers
                        <br> - And many more features...
                    </h4>
                </div>
            </div>

            <br><br>
            <!-- examples -->
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">

                    <div class="mdl-grid">
                        <div class="mdl-cell mdl-cell--12-col">
                            <h4 class="bc-accom-sub-title bc-text-center">  CHECK OUT SOME EXAMPLES BELOW:</h4>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="mdl-layout-spacer"></div>
    </div>


    <!-- Desktop -->
    <!-- Left Accommodations -->
    <div class="mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        <div class="mdl-cell mdl-cell--8-col bc-no-margin">
            <img class="bc-accom-img-main-left" src="{% static 'images/copenhagen3.jpg' %}" alt="">
        </div>

        <div class="mdl-cell mdl-cell--4-col bc-no-margin">
            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-top" src="{% static 'images/copenhagen-downtown-hostel.jpg' %}"
                     alt="">
            </div>

            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-bottom" src="{% static 'images/copenhagen2.jpg' %}" alt="">
            </div>
        </div>
    </div>   <!-- End Left Accommodations -->

    <!-- Right Accommodations -->
    <div class="mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        <div class="mdl-cell mdl-cell--4-col bc-no-margin">
            <div class="mdl-grid">
                <img class="bc-accom-img-side-left-top" src="{% static 'images/berlin3.jpg' %}" alt="">
            </div>

            <div class="mdl-grid">
                <img class="bc-accom-img-side-left-bottom" src="{% static 'images/berlin2.jpg' %}" alt="">
            </div>
        </div>

        <div class="mdl-cell mdl-cell--8-col bc-no-margin">
            <img class="bc-accom-img-main-right" src="{% static 'images/berlin.jpg' %}" alt="">
        </div>
    </div> <!-- Right Accommodations -->


    <!-- Left Accommodations -->
    <div class="mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        <div class="mdl-cell mdl-cell--8-col bc-no-margin">
            <img class="bc-accom-img-main-left" src="{% static 'images/hotel-allure.jpg' %}" alt="">
        </div>

        <div class="mdl-cell mdl-cell--4-col bc-no-margin">
            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-top" src="{% static 'images/amsterdam3.jpg' %}" alt="">
            </div>

            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-bottom" src="{% static 'images/amsterdam2.jpg' %}" alt="">
            </div>
        </div>
    </div>

    <!-- Right Accommodations -->
    <div class="mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        <div class="mdl-cell mdl-cell--4-col bc-no-margin">
            <div class="mdl-grid">
                <img class="bc-accom-img-side-left-top" src="{% static 'images/Garden-house.jpg' %}" alt="">
            </div>

            <div class="mdl-grid">
                <img class="bc-accom-img-side-left-bottom" src="{% static 'images/Garden-house3.jpg' %}" alt="">
            </div>
        </div>

        <div class="mdl-cell mdl-cell--8-col bc-no-margin">
            <img class="bc-accom-img-main-right" src="{% static 'images/Garden-house2.jpg' %}" alt="">
        </div>
    </div> <!-- Right Accommodations -->

    <!-- Left Accommodations -->
    <div class="mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        <div class="mdl-cell mdl-cell--8-col bc-no-margin">
            <img class="bc-accom-img-main-left" src="{% static 'images/africa.jpg' %}" alt="">
        </div>

        <div class="mdl-cell mdl-cell--4-col bc-no-margin">
            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-top" src="{% static 'images/africa3.jpg' %}" alt="">
            </div>

            <div class="mdl-grid">
                <img class="bc-accom-img-side-right-bottom" src="{% static 'images/africa2.jpg' %}" alt="">
            </div>
        </div>
    </div>

    <!-- Mobile Tablet -->
    <div class="mdl-grid mdl-cell--hide-desktop">
        <div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--hide-desktop">
            <img class="bc-standard-img" src="{% static 'images/copenhagen3.jpg' %}" alt="">
        </div>
        <div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--hide-desktop">
            <img class="bc-standard-img" src="{% static 'images/berlin.jpg' %}" alt="">
        </div>
        <div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--hide-desktop">
            <img class="bc-standard-img" src="{% static 'images/hotel-allure.jpg' %}" alt="">
        </div>
        <div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--hide-desktop">
            <img class="bc-standard-img" src="{% static 'images/Garden-house2.jpg' %}" alt="">
        </div>
        <div class="mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--hide-desktop">
            <img class="bc-standard-img" src="{% static 'images/africa.jpg' %}" alt="">
        </div>
    </div>


{% endblock %}

project/templates/frontpages/about/premium.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Premium Membership{% endblock %}

{% block content %}

    <div class="mdl-grid bc-site-grey-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--8-col">
            <h3 class="bc-text-center">Premium membership</h3>
            It's very cool to be premium, because:
            <br>
            1) <br>
            2) <br>
            If you ready to pay {{ premium_membership_price }}$ for LIFETIME premium membership, go <a
                href="{% url 'accounts:membership' %}">here</a>
        </div>

        <div class="mdl-layout-spacer"></div>
    </div>

{% endblock %}