project/Bctpython/urls.py
from ckeditor_uploader import views as ckeditor_views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache, cache_page
from frontpages import views
from .views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^quickbooks/', include('quickbooks.urls')),

    url(r'^$', views.home,  name='home'),

    url(r'^gallery/', cache_page(60 * 30)(views.GalleryInstagramView.as_view()),  name='gallery'),
    url(r'^yourtrips/', views.yourtrips, name='yourtrips'),
    url(r'^westeuro/', views.westeuro,  name='westeuro'),
    url(r'^easteuro/', views.easteuro, name='easteuro'),
    url(r'^scandinavia/', views.scandinavia,  name='scandinavia'),
    url(r'^kilimanjaro/', views.kilimanjaro, name='kilimanjaro'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.faqs, name='faqs'),
    url(r'^privacy/', views.privacy, name='privacy'),
    url(r'^thankyou/', views.thankyou, name='thankyou'),

    # about pages: terms, info pages, etc.
    url(r'^about/', views.about, name='about'),
    url(r'^included/', views.included,  name='included'),
    url(r'^packing/', views.packing, name='packing'),
    url(r'^accommodations/', views.accommodations, name='accommodations'),
    url(r'^guides/', views.guides,  name='guides'),
    url(r'^reviews/', views.reviews,  name='reviews'),
    url(r'^terms/', views.terms, name='terms'),
    url(r'^premium/', views.AboutPremiumView.as_view(), name='premium'),

    # ckeditor urls with rewrited decorators (staff required - standard decorator)
    url(r'^upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    # stripe webhooks
    url(r'webhooks/$', webhooks, name='webhooks'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'frontpages.views.handler400'
handler403 = 'frontpages.views.handler403'
handler404 = 'frontpages.views.handler404'
handler500 = 'frontpages.views.handler500'

project/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    # Account home page
    url(r'^$', views.UserHomePageView.as_view(), name='home'),
    url(r'public/(?P<pk>[-\w]+)/$', views.UserPublicView.as_view(), name='public-home'),
    url(r'^membership/$', views.UserMembershipView.as_view(), name='membership'),
    url(r'^membership/payment/$', views.membership_payment, name='membership_payment'),
    url(r'^membership/payment-success/$', views.PremiumMembershipPaymentSuccessView.as_view(),
        name='membership_success'),

    url(r'^trip/(?P<pk>[-\w]+)/$', views.UserTripDetail.as_view(), name='trip'),
    url(r'^payment-success/$', views.TripPaymentSuccessView.as_view(), name='trip_success'),
    url(r'^create-post/$', views.UserBlogPostCreateView.as_view(), name='create_blog_post'),
    url(r'^create-post/thanks/$', views.UserBlogPostCreatedView.as_view(), name='blog_post_created'),
    # url(r'^trip/$', views.usertripdetail, name='trip2'),
    # User sign up and account activation via email address
    url(r'^signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^account-activation-sent/$', views.account_activation_sent, name='account_activation_sent'),

    # Login and Logout pages for account
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logout'),

    # Update pages for User and Account models
    url(r'^update-account/$', views.AccountUpdate.as_view(), name='update_account'),
    url(r'^update-user/$', views.UserUpdate.as_view(), name='update_user'),

    # URLs for password change. password_change - page with form to input old password.
    url(r'^password-change/$', views.UserPasswordChangeView.as_view(), name='password_change'),
    url(r'^password-change-done/$', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    # URLs for password reset ('forgot password' functionality). _reset and _confirm - pages with forms
    url(r'^password-reset/$', views.UserPasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset-done/$', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password-reset-complete/$', views.UserPasswordResetComplete.as_view(), name='password_reset_complete'),

]

project/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogHomePageView.as_view(), name='home'),
    url(r'^(?P<pk>[-\w]+)/$', views.BlogPostPageView.as_view(), name='blog_post'),
]

project/lib/django/conf/project_template/project_name/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

project/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50, blank=False)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey('accounts.Account')
    category = models.ManyToManyField(Category, related_name='posts')
    title = models.CharField(max_length=200, blank=False)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(null=True, blank=True)
    is_draft = models.BooleanField(default=True)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title

project/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings

from .models import Post


class BlogHomePageView(ListView):
    model = Post
    template_name = 'blog/home.html'
    paginate_by = 2
    queryset = Post.objects.all().exclude(is_draft=True)


class BlogPostPageView(DetailView):
    model = Post
    template_name = 'blog/blog_post.html'

    def get_context_data(self, **kwargs):
        context = super(BlogPostPageView, self).get_context_data(**kwargs)
        context['disqus_embed_url'] = settings.DISQUS_EMBED_URL
        context['disqus_page_url'] = self.request.path
        context['disqus_page_identifier'] = self.object.pk

        return context

project/templates/blog/blog_post.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Blog - {{ post.title }}{% endblock %}

{% block content %}

    <div class="mdl-grid bc-site-grey-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--8-col">

            <div>
                <h1>{{ post.title }}</h1>
                <p>Date: {{ post.published_date|date:"d M Y" }}, Published by: <a
                        href="{% url 'accounts:public-home' pk=post.author.pk %}" target="_blank">{{ post.author }}</a>,
                    Category:
                    {% for category in post.category.all %}
                        {{ category }}
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </p>
                <p>{{ post.text|safe }}</p>
            </div>

            <div class="mdl-cell mdl-cell--12-col">
                <div class="bc-social-share">
                    <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button"
                         data-size="large" data-mobile-iframe="true"></div>
                    <div class="fb-follow" data-href="https://www.facebook.com/Blackcrowtours" data-height="28"
                         data-layout="button" data-size="large" data-show-faces="false"></div>
                    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text={{ post.title }}"
                       data-size="large">
                        <link rel="me" href="https://twitter.com/blackcrowtours">
                        Tweet</a>
                    <a class="twitter-follow-button" href="https://twitter.com/blackcrowtours" data-size="large"
                       data-show-count="false">Follow @blackcrowtours</a>
                </div>

                <div id="disqus_thread"></div>
                <script>
                    var disqus_config = function () {
                        this.page.url = '{{ request.build_absolute_uri }}';
                        this.page.identifier = '{{ disqus_page_identifier }}';
                    };

                    (function () { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = '{{ disqus_embed_url }}';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                    powered by Disqus.</a></noscript>
            </div>
        </div>

        <div class="mdl-layout-spacer"></div>
    </div>

{% endblock %}

project/templates/blog/blog_post_created.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Blog Post Created! Thank you!{% endblock %}

{% block content %}

    <div class="mdl-grid bc-site-grey-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--8-col">
            <div class="bc-text-center">
                <h4>Your blog post successfully created and sent for approval.<br>
                    After being approved, you will see your post in site <a href="{% url 'blog:home' %}">blog</a></h4>
                Back to <a href="{% url 'accounts:home' %}">your profile</a>
            </div>
        </div>

        <div class="mdl-layout-spacer"></div>
    </div>

{% endblock %}

project/templates/blog/create_blog_post.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Create Blog Post{% endblock %}

{% block content %}

    <div class="mdl-grid bc-site-grey-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--9-col mdl-shadow--2dp bc-about-pages-template-background">

            <!-- Section 1 Mission  -->
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--12-col">
                    <h4 class="bc-about-pages-title bc-text-center">- Create Blog Post -</h4>
                </div>


                {% if form.non_field_errors %}
                    <div class="mdl-cell mdl-cell--12-col">
                        <div class="bc-form-errors-alert" style="width: 100%;">{{ form.non_field_errors }}</div>
                    </div>
                {% endif %}


                <div class="mdl-cell mdl-cell--12-col">
                    <div class="mdl-grid">
                        <div class="mdl-layout-spacer"></div>
                        <div class="mdl-cell mdl-cell--10-col">
                            <form method="POST">
                                {% csrf_token %}

                                {% if form.title.errors %}
                                    <span class="bc-form-errors-alert"
                                          style="width: 100%">{{ form.title.errors }}</span>
                                {% endif %}

                                <div class="mdl-textfield mdl-js-textfield">
                                    <input class="mdl-textfield__input" type="text" name="title" id="id_title"
                                           style="width: 400px;"/>
                                    <label class="mdl-textfield__label bc-about-pages-para" for="id_title"
                                           style="width: 400px;">Title</label>
                                </div>

                                <div class="mdl-grid">
                                    <div class="mdl-cell mdl-cell--3-col">
                                        Choose post category:
                                    </div>
                                    <div class="mdl-cell mdl-cell--9-col">
                                        <div class="bc-multi-select">
                                            {{ form.category }}
                                        </div>
                                    </div>
                                </div>

                                <div class="mdl-grid">
                                    <div class="mdl-cell mdl-cell--12-col">
                                        {{ form.media }}
                                        {{ form.text }}
                                    </div>
                                    {% if form.text.errors %}
                                        <span class="bc-form-errors-alert"
                                              style="width: 100%">{{ form.text.errors }}</span>
                                    {% endif %}
                                </div>

                                <div class="mdl-grid">
                                    <div class="mdl-cell mdl-cell--12-col bc-text-center">
                                        <button type="submit" value="submit" name="submit"
                                                class="mdl-button mdl-js-button mdl-button--raised">
                                            Send for approval
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="mdl-layout-spacer"></div>
                    </div>
                </div>

            </div>

            <br>
            <hr>

        </div>

        <div class="mdl-layout-spacer"></div>
    </div>

{% endblock %}

project/templates/blog/home.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}- Blog{% endblock %}

{% block content %}

    <div class="mdl-grid bc-site-grey-background">
        <div class="mdl-layout-spacer"></div>

        <div class="mdl-cell mdl-cell--8-col">
            <div>
                <h1 class="bc-text-center">Black Crown Tours Blog</h1>
            </div>

            {% for post in object_list %}
                <div>
                    <h2><a href="{% url 'blog:blog_post' pk=post.pk %}">{{ post.title }}</a></h2>
                    <p>Date: {{ post.published_date|date:"d M Y" }}, Published by: <a
                            href="{% url 'accounts:public-home' pk=post.author.pk %}"
                            target="_blank">{{ post.author }}</a></p>
                    <p>Category:
                        {% for category in post.category.all %}
                            {{ category }}
                            {% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>
                    <p>{{ post.text|safe|truncatewords:50 }}</p>
                    <p><a href="{% url 'blog:blog_post' pk=post.pk %}">read entire post</a></p>
                </div>

            {% empty %}
                <div>
                    <p>No blog post here :(</p>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <div class="bc-text-center">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class=""><a href="blog/?page={{ page_obj.previous_page_number }}">
                                <i class="material-icons">keyboard_arrow_left</i></a>
                            </li>
                        {% else %}
                            <li class="disabled"><i class="material-icons">keyboard_arrow_left</i></li>
                        {% endif %}

                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="active"><span>{{ i }}</span></li>
                            {% else %}
                                <li><a href="blog/?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li><a href="blog/?page={{ page_obj.next_page_number }}">
                                <i class="material-icons">keyboard_arrow_right</i></a>
                            </li>
                        {% else %}
                            <li class="disabled"><i class="material-icons">keyboard_arrow_right</i></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="mdl-layout-spacer"></div>
    </div>

{% endblock %}